[files]
extend-exclude = [
    # Ignore third-party software comment typos
    "**/assets/*.z80",
]

[default.extend-words]
# DAA is a valid Z80 instruction word
DAA = "DAA"
# These are valid Z80 register pairs
IT = "IT"
IX = "IX"
IY = "IY"