[package]
name = "rustzx"
version = "0.10.0"
authors = ["Vladyslav Nikonov <mail@pacmancoder.xyz>"]
publish = false
description = "ZX Spectum emulator application"
repository = "https://github.com/pacmancoder/rustzx"
readme = "../README.md"
keywords = ["emulator", "game", "z80"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.34", features = ["unsafe_textures", "bundled", "static-link"] }
rustzx-core = { path =  "../rustzx-core", features = ["full"] }
log = "0.4"
anyhow = "1"
clap = "3.0.0-beta.2"
env_logger = "0.8"
