[package]
name = "rustzx"
version = "0.14.0"
authors = ["The RustZX contributors", "Vladyslav Nikonov <mail@pacmancoder.xyz>"]
description = "ZX Spectum emulator"
repository = "https://github.com/pacmancoder/rustzx"
readme = "../README.md"
keywords = ["emulator", "game", "z80"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.34", features = ["unsafe_textures", "bundled", "static-link"] }
rustzx-core = { version = "0.14", path =  "../rustzx-core", features = ["full"] }
rustzx-utils = { version = "0.14", path =  "../rustzx-utils", features = ["std"] }
log = "0.4"
anyhow = "1"
structopt = "0.3"
env_logger = "0.8"
