[package]
name = "rustzx"
version = "0.14.0"
authors = ["The RustZX contributors", "Vladyslav Nikonov <mail@pacmancoder.xyz>"]
description = "ZX Spectrum emulator"
repository = "https://github.com/pacmancoder/rustzx"
readme = "../README.md"
keywords = ["emulator", "game", "z80"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.34", features = ["unsafe_textures", "bundled", "static-link"] }
rustzx-core = { version = "0.14", path =  "../rustzx-core", features = ["full"] }
rustzx-utils = { version = "0.14", path =  "../rustzx-utils", features = ["std"] }
log = "0.4"
anyhow = "1"
structopt = "0.3"
strum = { version = "0.21", features = ["derive"] }
env_logger = "0.8"
cpal = { version = "0.13", default-features = false, optional = true }

[features]
default = ["sound-cpal"]
# cpal requries ALSA development headers on Linux, if this feature
# is disabled, RustZX will be built only with SDL audio backend support
sound-cpal = ["cpal"]
