[alias]
rustzx-fmt = "fmt --all"
rustzx-clippy = "clippy --workspace --all-features"
rustzx-run = "run --release --bin rustzx --"
rustzx-install = "install --path rustzx"
rustzx-build-assets = "run -p rustzx-test --bin build-assets"
