[package]
name = "rustzx-z80"
description = "Z80 CPU emulator library"
keywords = ["emulator", "z80", "no_std"]

version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dev-dependencies]
paste = "1.0"
